Repository nasa/CF, pull requests merged in 2022-02, with the labels that each got.

#185 Fix #138, Add Build Workflow
  .github/workflows/build-cfs.yml
Labels: continuous-integration, CCB:Approved

#187 Fix #186, CF table name and default polling disabled
  fsw/tables/cf_def_config.c
Labels: CCB:Approved

#189 Fix #188, Apply header guard standard
  unit-test/utilities/cf_test_utils.h
Labels: CCB:Ready

#191 Fix #190, Use lowercase and updated table name in CI
  .github/workflows/build-cfs.yml
Labels: CCB:Ready, continuous-integration

#198 Fix #197, Resolve uninitialized variables in UT
  unit-test/cf_app_tests.c
  unit-test/cf_chunk_tests.c
  unit-test/cf_clist_tests.c
  unit-test/cf_utils_tests.c
Labels: CCB:Approved

#196 Fix #195, Stack smashing in CF_Chunk unit test
  unit-test/cf_chunk_tests.c
Labels: unit-test, CCB:Approved
