Repository nasa/CF, pull requests merged in 2022-06, with the labels that each got.

#257 Fix #120 #256, Move timers into channel config and remove cfg telemetry
  docs/cf_FunctionalRequirements.csv
  fsw/src/cf_app.c
  fsw/src/cf_app.h
  fsw/src/cf_cfdp.c
  fsw/src/cf_cfdp_r.c
  fsw/src/cf_cfdp_s.c
  fsw/src/cf_cmd.c
  fsw/src/cf_cmd.h
  fsw/src/cf_msg.h
  fsw/src/cf_tbldefs.h
  fsw/tables/cf_def_config.c
  unit-test/cf_app_tests.c
  unit-test/cf_cfdp_r_tests.c
  unit-test/cf_cfdp_s_tests.c
  unit-test/cf_cmd_tests.c
Labels: CCB:Approved

#258 Fix #217, Add mission rev and print in startup and noop events
  fsw/platform_inc/cf_platform_cfg.h
  fsw/src/cf_app.c
  fsw/src/cf_cmd.c
  unit-test/cf_cmd_tests.c
Labels: CCB:Approved

#259 Fix #173, Truncate files when created to avoid stale data
  fsw/src/cf_cfdp_r.c
  fsw/src/cf_cmd.c
Labels: CCB:Approved

#255 Fix #254, Fix #220, Updates CLA information for Apache 2.0
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: CCB:Approved, docs

#261 Fix #260, Remove registration of empty EVS filters
  fsw/src/cf_app.c
Labels: CCB:Approved

#245 Fix #244, Add CodeQL
  .github/workflows/codeql-build.yml
Labels: CCB:Approved, dependency
