Repository nasa/CF, pull requests merged in 2022-08, with the labels that each got.

#305 Fix #296, Consistent CFE_EVS_SendEvent handling in UT
  unit-test/CMakeLists.txt
  unit-test/cf_app_tests.c
  unit-test/cf_cfdp_dispatch_tests.c
  unit-test/cf_cfdp_r_tests.c
  unit-test/cf_cfdp_s_tests.c
  unit-test/cf_cfdp_sbintf_tests.c
  unit-test/cf_cfdp_tests.c
  unit-test/cf_cmd_tests.c
  unit-test/cf_utils_tests.c
  unit-test/utilities/cf_test_utils.c
  unit-test/utilities/cf_test_utils.h
Labels: CCB:Approved

#295 Fix #224, support dynamic pdu packets
  fsw/src/cf_cfdp_sbintf.c
  fsw/src/cf_cfdp_sbintf.h
  fsw/src/cf_cfdp_types.h
  unit-test/cf_cfdp_sbintf_tests.c
Labels: CCB:Approved

#300 Fix #299, Clarify event text for commands that initiate actions
  fsw/src/cf_cmd.c
Labels: CCB:Approved

#304 Fix #301, Remove file dequeue cmd requirements
  docs/cf_FunctionalRequirements.csv
Labels: CCB:Approved

#303 Fix #213, updated CFDP class validation
  fsw/src/cf_cmd.c
  unit-test/cf_cmd_tests.c
Labels: CCB:Ready

#302 Fix #274, send packet when transaction resets
  docs/cf_FunctionalRequirements.csv
  fsw/platform_inc/cf_msgids.h
  fsw/src/cf_cfdp.c
  fsw/src/cf_cfdp.h
  fsw/src/cf_msg.h
  unit-test/cf_cfdp_tests.c
Labels: CCB:Approved

#309 Fix #308, Revert requirements whitespace changes from #302
  docs/cf_FunctionalRequirements.csv
Labels: CCB:Approved

#307 Fix #293 #306, CF chunk unit test cleanup and main code chunk add and gap bug fixes
  fsw/src/cf_chunk.c
  fsw/src/cf_chunk.h
  unit-test/cf_chunk_tests.c
  unit-test/utilities/cf_test_utils.h
Labels: CCB:Approved

#312 Fix #311, Use fixed size types in tlm EOT packet
  fsw/src/cf_msg.h
Labels: CCB:Approved

#310 Fix #277, Detect pdu truncation
  docs/cf_FunctionalRequirements.csv
  fsw/src/cf_cfdp.c
  fsw/src/cf_codec.c
  fsw/src/cf_codec.h
  fsw/src/cf_events.h
  unit-test/cf_cfdp_tests.c
  unit-test/cf_codec_tests.c
  unit-test/stubs/cf_codec_stubs.c
Labels: CCB:Approved

#314 Fix #313, removes CF_CONFIG_TLM_MID from cf_msgids.h
  fsw/platform_inc/cf_msgids.h
Labels: enhancement, CCB:Approved

#318 Fix #317, use UtAssert_INT32_EQ to check status
  unit-test/cf_codec_tests.c
Labels: CCB:Approved

#320 Fix #319, Disable polling directory in default table
  fsw/tables/cf_def_config.c
Labels: CCB:Approved

#316 Fix #315, Remove dynamic memory use in UTs
  unit-test/cf_clist_tests.c
  unit-test/cf_crc_tests.c
  unit-test/utilities/cf_test_utils.h
Labels: CCB:Approved
