Repository nasa/CF, pull requests merged in 2022-03, with the labels that each got.

#201 Fix #200, Follow include standard
  fsw/src/cf_logical_pdu.h
Labels: CCB:Ready

#205 Fix #93, Adds format check and static analysis workflows
  .github/workflows/format-check.yml
  .github/workflows/static-analysis.yml
Labels: CCB:Approved

#209 Fix #204, Doxygen frontpage refactor and cleanup
  README.md
  cf_doxygen_config.txt
  docs/cf-detaildesign.doxyfile.in
  docs/cf_guide.md
  docs/dox_src/CMakeLists.txt
  docs/dox_src/cf-common.doxyfile.in
  docs/dox_src/cf-usersguide.doxyfile.in
  docs/dox_src/cfs_cf.dox
  fsw/mission_inc/cf_perfids.h
  fsw/platform_inc/cf_msgids.h
  fsw/platform_inc/cf_platform_cfg.h
  fsw/platform_inc/cf_tbldefs.h
  fsw/src/cf_app.h
  fsw/src/cf_assert.h
  fsw/src/cf_cfdp.h
  fsw/src/cf_cfdp_dispatch.h
  fsw/src/cf_cfdp_pdu.h
  fsw/src/cf_cfdp_r.h
  fsw/src/cf_cfdp_types.h
  fsw/src/cf_chunk.h
  fsw/src/cf_clist.h
  fsw/src/cf_codec.h
  fsw/src/cf_events.h
  fsw/src/cf_logical_pdu.h
  fsw/src/cf_msg.h
  fsw/src/cf_timer.h
  fsw/src/cf_utils.h
  fsw/src/cf_version.h
  mission_build.cmake
Labels: CCB:Approved, docs

#208 Fix #207, Remove old license headers
  unit-test/stubs/cf_app_global.c
  unit-test/stubs/cf_cfdp_handlers.c
  unit-test/stubs/cf_cfdp_sbintf_handlers.c
  unit-test/stubs/cf_chunk_handlers.c
  unit-test/stubs/cf_clist_handlers.c
  unit-test/stubs/cf_cmd_handlers.c
  unit-test/stubs/cf_utils_handlers.c
Labels: CCB:Approved

#211 Fix #210, Apply clang-format-10 whitespace formatting
  fsw/src/cf_app.c
  fsw/src/cf_cfdp.c
  fsw/src/cf_cfdp_dispatch.c
  fsw/src/cf_cfdp_r.c
  fsw/src/cf_cfdp_r.h
  fsw/src/cf_cfdp_s.c
  fsw/src/cf_cfdp_sbintf.c
  fsw/src/cf_cfdp_types.h
  fsw/src/cf_chunk.c
  fsw/src/cf_chunk.h
  fsw/src/cf_cmd.c
  fsw/src/cf_codec.c
  fsw/src/cf_codec.h
  fsw/src/cf_logical_pdu.h
  fsw/src/cf_utils.c
  fsw/src/cf_utils.h
  unit-test/cf_app_tests.c
  unit-test/cf_cfdp_dispatch_tests.c
  unit-test/cf_cfdp_r_tests.c
  unit-test/cf_cfdp_s_tests.c
  unit-test/cf_cfdp_sbintf_tests.c
  unit-test/cf_cfdp_tests.c
  unit-test/cf_chunk_tests.c
  unit-test/cf_clist_tests.c
  unit-test/cf_cmd_tests.c
  unit-test/cf_crc_tests.c
  unit-test/cf_utils_tests.c
  unit-test/stubs/cf_cfdp_handlers.c
  unit-test/utilities/cf_test_alt_handler.c
  unit-test/utilities/cf_test_utils.c
  unit-test/utilities/cf_test_utils.h
  unit-test/utilities/ut_utils_cfe_hooks.h
Labels: CCB:Ready
