Repository nasa/CF, pull requests merged in 2023-09, with the labels that each got.

#405 Fix #351, Removes semi-colon in TEST_CF_ADD macro
  unit-test/utilities/cf_test_utils.h
Labels: enhancement, CCB:Approved

#407 Fix #406, Pass in correct CF_EotPacket_t size to msg
  fsw/src/cf_cfdp.c
Labels: bug, CCB:Approved

#332 Fix #265, change variable names to be more informative
  fsw/src/cf_cfdp.c
  fsw/src/cf_cfdp.h
  fsw/src/cf_cfdp_dispatch.c
  fsw/src/cf_cfdp_dispatch.h
  fsw/src/cf_cfdp_r.c
  fsw/src/cf_cfdp_r.h
  fsw/src/cf_cfdp_s.c
  fsw/src/cf_cfdp_s.h
  fsw/src/cf_cfdp_sbintf.c
  fsw/src/cf_cfdp_sbintf.h
  fsw/src/cf_cfdp_types.h
  fsw/src/cf_chunk.c
  fsw/src/cf_chunk.h
  fsw/src/cf_clist.c
  fsw/src/cf_cmd.c
  fsw/src/cf_cmd.h
  fsw/src/cf_crc.c
  fsw/src/cf_crc.h
  fsw/src/cf_timer.c
  fsw/src/cf_timer.h
  fsw/src/cf_utils.c
  fsw/src/cf_utils.h
  unit-test/cf_cfdp_dispatch_tests.c
  unit-test/cf_cfdp_r_tests.c
  unit-test/cf_cfdp_s_tests.c
  unit-test/cf_cfdp_sbintf_tests.c
  unit-test/cf_cfdp_tests.c
  unit-test/cf_cmd_tests.c
  unit-test/cf_crc_tests.c
  unit-test/cf_timer_tests.c
  unit-test/cf_utils_tests.c
  unit-test/stubs/cf_app_stubs.c
  unit-test/stubs/cf_cfdp_dispatch_stubs.c
  unit-test/stubs/cf_cfdp_handlers.c
  unit-test/stubs/cf_cfdp_r_stubs.c
  unit-test/stubs/cf_cfdp_s_stubs.c
  unit-test/stubs/cf_cfdp_sbintf_stubs.c
  unit-test/stubs/cf_cfdp_stubs.c
  unit-test/stubs/cf_chunk_handlers.c
  unit-test/stubs/cf_cmd_stubs.c
  unit-test/stubs/cf_crc_stubs.c
  unit-test/stubs/cf_timer_stubs.c
  unit-test/stubs/cf_utils_handlers.c
  unit-test/stubs/cf_utils_stubs.c
  unit-test/utilities/cf_test_alt_handler.c
  unit-test/utilities/cf_test_utils.h
Labels: CCB:Approved
